import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class CGITestCase {

	@Test
	public void test() {
		ConveyGameOfLife convey=new ConveyGameOfLife();
		System.out.println("======TEST ONE EXECUTED=======");
	    /*   Assertions.assertEquals("CurrentGenration" == convey.print());
	       Assertions.assertEquals("..........");
	    		   ...**.....
	    		   ....*.....
	    		   ..........
	    		   ..........
	    		   ...**.....
	    		   ..**......
	    		   .....*....
	    		   ....*.....
	    		   ..........
	    		   NextGenration
	    		   ..........
	    		   ...**.....
	    		   ...**.....
	    		   ..........
	    		   ..........
	    		   ..***.....
	    		   ..**......
	    		   ...**.....
	    		   ..........
	    		   ..........");*/
	}

}
